name: Build and Release Windows Executable

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v4
      #----------------------------------------------
      #  -----  install & configure poetry  -----
      #----------------------------------------------
      - name: Set up python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          # cache: poetry
      - name: Install Poetry
        run: |
          pipx install poetry

      -name: Check environment
        run: |
          python --version
          poetry --version

      # - name: Install dependencies
      #   run: poetry install
      #
      # - name: Build Windows executable
      #   run: |
      #     poetry run pyinstaller --onefile --icon=media/icon.ico --add-data "parfile/gui;parfile/gui" parfile/app.py
      #
      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: v1.0.0  # Set your desired tag name
      #     release_name: Release 1.0.0  # Set your desired release name
      #     body: |
      #       Windows release
      #
      #     draft: false
      #     prerelease: false
