name: Build and Deploy

on:
  push:
    branches:
      - main  # Adjust if your main branch has a different name
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    outputs:
      version: ${{ steps.step_version.outputs.version }}
      upload_url: ${{ steps.step_upload_url.outputs.upload_url }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Adjust to the Python version you're using

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install dependencies
      run: poetry install

    - name: Add pyinstaller
      run: poetry add pyinstaller

    - name: Build executable
      run: poetry run pyinstaller --onefile --windowed --icon=media/icon.ico --add-data "parfile/gui:parfile/gui" parfile/app.py --name parfile

    - name: Upload to Releases
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ needs.build.outputs.upload_url }}
        asset_path: ./dist/parfile.exe  # Adjust if the path to your built executable is different
        asset_name: parfile.exe
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

