
name: Build and Release Windows Executable


on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Poetry
        run: |
          pipx install poetry

      - name: Check enviroment
        run: |
          python -V
          poetry --version

      - name: Install dependencies
        run: |
          poetry install
          poetry add pyinstaller

      - name: Build Windows executable
        run: |
          poetry run pyinstaller --onefile --windowed --icon=media/icon.ico --add-data "parfile/gui:parfile/gui" parfile/app.py --name parfile

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: executable
          path: ./dist/parfile.exe  # Adjust the path to your executable file
