name: Build and Release Windows Executable

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pipx install poetry
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - name: Check enviroment
        run: |
          python -V
          poetry --version

      - name: Install dependencies
        run: |
          poetry install
          poetry add pyinstaller

      - name: Build Windows executable
        run: |
          poetry run pyinstaller --onefile --windowed --icon=media/icon.ico --add-data "parfile/gui:parfile/gui" parfile/app.py --name parfile

